### ISSUE TITLE
Make policy-examples information part of table of contents!

### ISSUE THREAD

**Issue by robbieorvis** [JGCRI/gcam-doc#101]
I just discovered there is a page that details how to design policies for GCAM (https://jgcri.github.io/gcam-doc/policies_examples.html#linked-policy).

This page is not searchable from the Table of Contents of the docs, and I only accidentally just discovered it by clicking on a buried hyperlink. It would have saved me dozens of hours over the last year of trying to figure this out for myself.

Please, please, please add this to the table of contents at a minimum, and consider just adding the content to the policies page of the docs.

**Comment by pralitp** [comment]
> This page is not searchable from the Table of Contents

Yup, that was a mistake.  I'll fix that.

> It would have saved me dozens of hours over the last year of trying to figure this out for myself.

Well.. we actually just wrote it within the last month or so but we do appreciate that it was long overdue.

**Comment by robbieorvis** [comment]
Ah, okay. Well, then - that's great, thank you for writing it!
