### ISSUE TITLE
run run-gcam.bat errors!

### ISSUE THREAD

**Issue by LyyDandelion** [JGCRI/gcam-doc#107]
error:
-------------      start  --------------------------------
Running GCAM model code base version 5.2 revision gcam-v5.2

Configuration file:  configuration.xml
Parsing input files...
Error occurred during initialization of VM
Unable to load native library: Can't find dependent libraries
------------------ end    -----------------------------

The jar files imported by the project are copied to the JRE directory，But to no avail ;
I didn't know quite how to work on it

**Comment by kvcalvin** [comment]
If this is still an issue, please post it on `github.com/jgcri/gcam-core`. This repo is for documentation only, not model run errors.
