### ISSUE TITLE
How to disaggregate a region for a country to stand out as a separate region

### ISSUE THREAD

**Issue by ebakojoseph** [JGCRI/gcam-doc#116]
I am presently working on the Western Africa region and I would like to run the model on a specific sector of the energy sector of my country. How do I bring out the country as a single region?

**Comment by kvcalvin** [comment]
We have included instructions on how to separate an individual country on this page: https://github.com/JGCRI/gcamdata/wiki/Modifying-GCAM-via-the-Data-System. Note that you will need access to the IEA data to do this.

**Comment by ebakojoseph** [comment]
Thank you very much. I found all the information I needed.
