### ISSUE TITLE
Need a list of GCAM publications

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcam-doc#12]
On the index page the last broken link (after current branches get merged) is:
`[Full list of GCAM publications](http://wiki.umd.edu/gcam/index.php/References)`

I'm not sure where we should point this to.  Maybe we can recreate this from the old on from the wiki.  It is still there under but would need to be cleaned up.
v3.2/References.html

**Comment by rplzzz** [comment]
I'll knock this out right quick here.
