### ISSUE TITLE
Inputs syntax issue / CEDS issue

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcam-doc#128]
There is a simple format issue in the link `Historical non-CO<sub>2</sub> emissions information is provided in several files within the [CEDS folder]((https://github.com/JGCRI/gcam-core/blob/master/input/gcamdata/inst/extdata/emissions/CEDS).`

But in general, I'm not sure it is exactly right because the bulk of the CEDS data is "proprietary data" and not included in the repo.  What do we want to say about this?

**Comment by ssmithClimate** [comment]
Perhaps we re-write this as:

Historical non-CO<sub>2</sub> emissions information is provided in the GCAM release as "pre-built" data aggregated to GCAM regions, technologies, and fuels. Users that want to build using CEDS raw data, for example to build for different regional aggregations, will need to generate CEDS data using the open-source [CEDS system](https://github.com/JGCRI/CEDS) and place the resulting emissions data by country, fuel, and sector within the [CEDS folder]((https://github.com/JGCRI/gcam-core/blob/master/input/gcamdata/inst/extdata/emissions/CEDS).

**Comment by kvcalvin** [comment]
I've created a branch with this fix in it. I'm going to address several more small issues in that branch before I open a PR though.

**Comment by kvcalvin** [comment]
Fixed in https://github.com/JGCRI/gcam-doc/pull/130
