### ISSUE TITLE
Mainpage GCAM-USA link broken

### ISSUE THREAD

**Issue by ssmithClimate** [JGCRI/gcam-doc#129]
Here:

https://jgcri.github.io/gcam-doc/

https://jgcri.github.io/gcam-doc/gcam_usa.html

should be:

https://jgcri.github.io/gcam-doc/gcam-usa.html

**Comment by kvcalvin** [comment]
I've created a branch with this fix in it. I'm going to address several more small issues in that branch before I open a PR though.

**Comment by kvcalvin** [comment]
Fixed in https://github.com/JGCRI/gcam-doc/pull/130
