### ISSUE TITLE
Document policy cases

### ISSUE THREAD

**Issue by rjplevin** [JGCRI/gcam-doc#21]
Provide examples of all major policy types, e.g., (borrowing from Dan Loughlin's GUI demo):
- Air pollutant taxes or caps
- GHG taxes or caps
- CAFE standard
- Renewable Electricity Standard
- Technology subsidies
- Forced technology penetration
- High-efficiency technology end-use requirements
- Fuel carbon-intensity standards

Examples with full explanation on-line would be great. Ideally, these would also appear with each GCAM release in the policy dir. (These would also help me develop the code to support the GUI.)

**Comment by robbieorvis** [comment]
Seconding Rich's request for this documentation. It would be highly valuable.
