### ISSUE TITLE
Review process for pull requests

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/gcam-doc#3]
We need to decide how we are going to review and approve pull requests for GCAM documentation.  Things we need to consider:
- **How should we choose reviewers for pull requests and how many should we have?** Experience with code repositories has shown that if it isn't explicitly somebody's job to review PRs, then they just languish.
- **How do we manage doc changes for features that haven't been released yet?** That is, we probably need an aggregation branch for model changes that have been approved but not yet released.  Since we can't change the target of PRs on GitHub, it would be nice to get this straight ahead of time.

**Comment by pralitp** [comment]
My thoughts:
For documentation pull requests that are part of a core model proposal it would be made explicit at the time of deciding who the reviewers of the proposal are (like how we assign the code reviews).

For pull requests just for the sake of improving documentation: Please don't make us write a core model proposal. Is it possible to have someone someone notified _anytime_ a pull request is opened?  If so we could make Leon do this and have him assign it to someone (like how we assign core model proposals).

With regards to changing the target of the pull request it seems it should be possible:
https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository

**Comment by pralitp** [comment]
Nope, I think I am mistaken about changing the pull request target after it is already open.  What if we just did the PR merge manually to the branch we actually wanted?  Or I guess we could just reject it and have them open a new one targeting the correct branch?

**Comment by bpbond** [comment]
Other repos I'm involved with have a round-robin system for reviewing PRs. I absolutely agree that it has to be explicit or things won't get done.

I agree with @pralitp - documentation pull requests shouldn't need a core model proposal. (Nor, for that matter, should trivial, e.g. comments, code changes.)

There isn't an aggregation or dev branch already? Ah, you mean here on GitHub versus on our BitBucket?

**Comment by rplzzz** [comment]
Honestly, I'd like to keep the process as lightweight as possible.  It's already a difficult enough challenge to get people to actually write documentation, and if we make the review process onerous then people will _definitely_ never do it.  What I was hoping to do was come up with some sort of board of editors and have two of them read each documentation PR, make suggestions, and approve promptly.  

The review needs for documentation are much less than those for code (because it doesn't have to compile, run, or produce correct results), and the process should reflect that.  Rejecting a documentation change should be pretty rare, and should really only happen in cases of factual incorrectness or failing to meet professional standards.  Even incompleteness isn't really a reason to reject, since the documentation could always be expanded later.  I suppose in cases where documentation is being written in conjunction with a core model proposal, we could have the reviewers send a note back to whomever is reviewing the core model proposal that the new feature is still not adequately documented.

Anyhow, round robin seems like a reasonable way to go.  @bpbond, do your other repos maintain some sort of reviewer roster so that people know whose turn it is?

As for the aggregation branch for new feature documentation, that's mainly just a matter of communicating our expectations to the people doing the writing so that they pick the right branch when they create the pull request.

**Comment by bpbond** [comment]
I just checked - the main one I was thinking of uses a Google Docs spreadsheet, with each PR submitter tagging the next person in a rotating list. You could also use a 'permanent' issue too, I guess, using comments to tag the next person.

**Comment by bpbond** [comment]
> Honestly, I'd like to keep the process as lightweight as possible.

Agreed!

**Comment by rplzzz** [comment]
Hmm.  Maybe we'll try the permanent issue idea, so as not to introduce yet another toolset.  Anyone have any ideas on who else we could draft as a reviewer, besides the four of us?  The bigger the pool, the less work this will be for us.

**Comment by pralitp** [comment]
I guess I'm torn about the rotating through a pool of editors idea.  It seems more appropriate that if someone is making edits to some section such as transportation somebody who knows something about transportation should review the changes to make sure they make sense from a content perspective.

With that being said this will likely lock us into the same few number of people reviewing edits over and over again.

**Comment by bpbond** [comment]
I doubt there will always be the depth to review documentation in that way–e.g., to have transportation documentation always reviewed by transportation specialists–and would suggest instead a larger, more general pool, reviewing doc PRs for "is this clearly written?" and "does this make sense?". Let the scientific literature process answer "is this state-of-the-art for the discipline?".

I agree with @rplzzz let's not introduce another toolset.

**Comment by rplzzz** [comment]
Ben took the words right out of my mouth.  If we have more than one expert on some aspect of the model, odds are we are going to have them collaborate on writing the documentation.  We have to have faith that they will get the factual content right.  The purpose of the review is two-fold.  First, to make sure that the tone and style are appropriate for our public-facing documentation, and second to make sure that the detail and clarity are sufficient for it to be useful for people who don't already know the subject.  

This second point has been a real problem for us in the past (in this writer's humble opinion).  Experts on various parts of the model write documentation for each other, and a lot of what they write winds up being not very useful for anyone who lacks context and deep understanding of the subject that they have.  Probably the thing we need most is the review from the POV of an intelligent colleague not familiar with your work.

Finally, keep in mind that there is nothing stopping anyone who wants to weigh in on a subject from doing so, whether by commenting on the PR or by making adjustments and changes directly to the PR branch.
