### ISSUE TITLE
Some anchor links to sections that were numbered are now broken

### ISSUE THREAD

**Issue by pralitp** [JGCRI/gcam-doc#30]
It appears that at some update of Github pages sections such as:
```
### 4.2 Building with Xcode
```

Used to generate an id as `building-with-xcode` and now it is `42-building-with-xcode`.  We need to update anchor links accordingly.

**Comment by rplzzz** [comment]
I thought we had done this in the latest round of updates.  @pralitp, can you confirm or deny?

**Comment by pralitp** [comment]
I haven't done anything to remedy this issue yet I do plan on getting to it today
