### ISSUE TITLE
Regional GDP equation 

### ISSUE THREAD

**Issue by mbins** [JGCRI/gcam-doc#70]
I have found two potential issues with the documentation surrounding the regional GDP equation in `gcam-doc/macro-econ.md` (Equation 1).

`Equation1:  GDPr,t+1 = POPr,t+1 * (1+GROr,t)^tStep * (GDPr,t / POPr,t) * Pαr,t+1`

1. Equation 1 has the `Pαr,t+1` term at the end, but it’s not defined or explained anywhere.  I see that an explanation of this existed in previous versions of the documentation (see, for example, `gcam-doc/v4.4/macro-econ.md`), but not in the current version.  This is a bit confusing – I suggest either resurrecting this explanation or removing the `Pαr,t+1`  term from the equation.

2. Equation 1 lists GDP as a function of `GROr,t`, which I interpret as the labor productivity growth rate from the period prior to which GDP is being calculated (using a specific example, I interpret this as saying `GDPr,2015 = POPr,2015 * (1+GROr,2010)^5 * (GDPr,2010 / POPr,2010)` ).  I believe this is incorrect; my understanding is that the labor productivity growth rate for the 2015 period is used to calculate GDP in 2015.

**Comment by swaldhoff** [comment]
1. Yes, the explanation from the older version should probably be added back in. The text I have is: 

"While in general it is not implemented, an energy-feedback elasticity is included in the present formulation. The present feedback is determined by the term: Pαr,t+1Pr,t+1α, where PP is the aggregate price of energy service, calculated in the energy system component of the model and αα is the GDP feedback elasticity (Edmonds and Reilly, 1983). It is the percentage change in the GDP for a one-percent change in the price of energy services. The value is set to zero by default, which effectively removes this term from the determination of GDP, but if non-zero values are used, these values would be negative."

2. I think Matthew is correct (based on the xml files--I wouldn't know where to look/read the C++ code), GDP is calculated from the labor productivity growth rate in the sane period.

**Comment by kvcalvin** [comment]
I have addressed this in the `doc-reorg` branch.
